### ISSUE TITLE
Resume Dev OneOps Instance Development

### ISSUE THREAD

**Issue by ohall** [GRT/onesie#53]
Need to catch up with @tjsampson as to where we left off with the GRT OneOps instance, so we can see what it will take to get the effort moving forward again.

**Comment by tjsampson** [comment]
@ohall, We haven't touched the OneOps Instance for a few weeks now. It's still up on AWS, but it's in a stopped state. The ip address is 54.175.157.58, but I'm not sure who all has ssh access to the box. If there is anyone that needs SSH access, let me know, and I can create a generic user account with all of our SSH keys, or create individual accounts as necessary. Also, is there a place where we all have our public SSH keys floating around? We may want to create a page and document those somewhere, so that we have easy access for everyone. 

The last time we were on the OneOps instance, everything was working, except for the actual deployment. That will probably require some cycles from one of us to get that going.

**Comment by ohall** [comment]
![screen shot 2016-09-30 at 7 21 21 am](https://cloud.githubusercontent.com/assets/848113/18994846/8742c3ca-86de-11e6-8b63-6ad46011ec5d.png)

**Comment by ohall** [comment]
Docs
http://oneops.github.io/admin/getting-started/

**Comment by ohall** [comment]
http://ec2-54-158-29-230.compute-1.amazonaws.com:3000/ BOOM
